apiVersion: v1
kind: Namespace
metadata:
  name: apache-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-apache-log
  namespace: apache-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs_storage/apache-log
    server: 192.168.1.40
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-apache-log
  namespace: apache-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: apache-app
  labels:
    app: apache
spec:
  containers:
    - name: apache
      image: httpd:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: log-volume
          mountPath: "/var/log/apache"
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: nfs-apache-log
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: apache-app
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: apache