---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs_storage/gitlab/postgres
    server: 192.168.1.40
    readOnly: false

