# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "nfs-server" do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "nfs-server"
    config.vm.network "private_network", ip: "192.168.1.40", :adapter => 2
    config.vm.box_check_update = false
    config.vm.disk :disk, name: "disk1", size: "10GB", primary: true

    config.vm.provider "virtualbox" do |vb|
      vb.name = "nfs-server"
      vb.cpus = 2
      vb.memory = "2048"  # Customize the amount of memory on the VM:
      vb.gui = false # Display the VirtualBox GUI when booting the machine
    end
  end

  # Provision
  config.vm.provision "shell", inline: <<-SHELL
    # 실습용 계정 생성
    useradd -m -s /bin/bash -p $(perl -e 'print crypt("k8s", "salt")') k8s
    usermod -aG sudo k8s

    # git clone
    runuser -l k8s -c 'git clone https://github.com/grollcake/k8s-practice.git'

    # hosts 이름 등록 등
    bash /home/k8s/k8s-practice/p1-virtualbox-setup/scripts/init.sh

    # nfs server 설치
    bash /home/k8s/k8s-practice/p9-persistent-volume/scripts/nfs-server-setup.sh 
  SHELL
end
