kind: "Service"
apiVersion: "v1"
metadata:
  name: "redis-master"
  namespace: todo-app
  labels:
    app: "redis-master"
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: "TCP"
  selector:
    app: "redis-master"
