---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: wikijs-app
  labels:
    app: wikijs
spec:
  ports:
    - port: 5432
  selector:
    app: wikijs
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-wikijs-postgres
  namespace: wikijs-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: wikijs-app
  labels:
    app: wikijs
spec:
  selector:
    matchLabels:
      app: wikijs
      tier: db
  template:
    metadata:
      namespace: wikijs-app
      labels:
        app: wikijs
        tier: app
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: wikijs
            - name: POSTGRES_DB
              value: wikijs_production
            - name: POSTGRES_PASSWORD
              value: wikijs
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: pv-wikijs-postgres
